export const TOC_ITEMS = [
  { page: 1, title: "カバー", desc: "", section: "" },
  { page: 2, title: "目次", desc: "", section: "" },
  { page: 4, title: "たったひとつの絵の描き方", desc: "", section: "" },
  { page: 6, title: "林檎のスケッチ", desc: "", section: "" },
  { page: 8, title: "蜜柑（演習）", desc: "", section: "" },
  { page: 10, title: "ポーズマニアックス", desc: "", section: "" },
  { page: 12, title: "人物スケッチ（演習）", desc: "", section: "" },
  { page: 14, title: "バナナのスケッチ", desc: "", section: "" },
  { page: 16, title: "マグカップ（演習）", desc: "", section: "" },
  { page: 18, title: "犬", desc: "", section: "" },
  { page: 20, title: "遠近法の仕組み", desc: "", section: "" },
  { page: 22, title: "消失点とアイレベル", desc: "", section: "" },
  { page: 24, title: "坂道の消失点", desc: "", section: "" },
  { page: 26, title: "自然なパース", desc: "", section: "" },
  { page: 28, title: "魚眼レンズ", desc: "", section: "" },
  { page: 30, title: "風景のスケッチ", desc: "", section: "" },
  { page: 32, title: "裏表紙", desc: "", section: "" },
];